FROM ghcr.io/whynotea/devcontainer-base:v1.0.8

USER root
RUN curl -L https://go.dev/dl/go1.20.5.linux-amd64.tar.gz | tar -C /usr/local -xz
USER code
RUN zsh -ic "go install golang.org/x/tools/gopls@latest && \
             go install honnef.co/go/tools/cmd/staticcheck@latest && \
             go install golang.org/x/lint/golint@latest && \
             go install github.com/mgechev/revive@latest && \
             go install github.com/go-delve/delve/cmd/dlv@latest && \
             go install github.com/fatih/gomodifytags@latest && \
             go install github.com/haya14busa/goplay/cmd/goplay@latest && \
             go install github.com/cweill/gotests/gotests@latest && \ 
             go install github.com/josharian/impl@latest && \
             go install github.com/goreleaser/goreleaser@v1.25.1 && \
             go install github.com/sigstore/cosign/v2/cmd/cosign@v2.1.1 && \
             go install github.com/anchore/syft/cmd/syft@v0.85.0 && \
             chmod -R +w /home/code/go/pkg && \
             rm -rf /home/code/go/pkg && \
             vim --headless '+q!'"
